import { FC } from "react";
import { User } from "@/types";
import { isLoggedIn } from "@/utils";
import Head from "next/head";

type Props = {
  userData: User;
};

const Home: FC<Props> = ({ userData }) => {
  return (
    <>
      <Head>
        <title>Chat Room</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <aside className="sidebar">
          <h2>Chat Rooms</h2>
          <button>New Chat</button>
        </aside>
        <main className="main-content">
          <header className="chat-header">
            <h1>Welcome to the Chat</h1>
          </header>
          <div className="chat-area"></div>
          <form id="chat-form" autoComplete="off">
            <input type="text" id="message" placeholder="Type a message..." />
            <button type="submit">Send</button>
          </form>
        </main>
      </div>
    </>
  );
};

export default Home;

export async function getServerSideProps({ req }) {
  const userData = isLoggedIn(req);
  if (userData) {
    return {
      props: {
        userData,
      },
    };
  } else {
    return {
      props: {},
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }
}
